---

- name: add new sysctl values
  sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    state: "{{ item.state | default(omit) }}"
    reload: "{{ sysctl_reload }}"
  loop: "{{ sysctl_list }}"
