---

- hosts: all
  name: 'Verify'
  become: True
  gather_facts: True
  vars:
    __verify_sysctlcmd_by_os_family:
      Debian: 'cat /proc/sys/vm/swappiness | grep -q "17"'
      OpenBSD: 'sysctl kern.maxproc | grep -q "kern.maxproc=1017"'

    __verify_sysctlcontent_by_os_family:
      Debian: 'vm.swappiness=17'
      OpenBSD: 'kern.maxproc=1017'

  tasks:
    - name: 'Check /etc/sysctl.conf content'
      slurp:
        path: '/etc/sysctl.conf'
      register: __verify_file
      failed_when: not __verify_file['content'] | b64decode | regex_search(__verify_sysctlcontent_by_os_family[ ansible_facts['os_family'] ], multiline=True)

    - name: 'Check sysctl command'
      shell: "{{ __verify_sysctlcmd_by_os_family[ ansible_facts['os_family'] ] }}"
      register: __verify_cmd
      failed_when: __verify_cmd.rc != 0
